# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='article_download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_file_path', models.CharField(max_length=250)),
                ('article_download_created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('article_download_last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_parsed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='article_parsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('published_date', models.DateTimeField(blank=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_update_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('unique_id', models.IntegerField(unique=True)),
                ('article_download_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_avm.article_download')),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=250)),
                ('article_parsed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_avm.article_parsed')),
            ],
        ),
        migrations.CreateModel(
            name='map_unresolved_resolved_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='map_unresolved_resolved_news_type_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='resolved_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_location_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='resolved_news_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_news_type_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=250, unique=True)),
                ('source_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='unresolved_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unresolved_location_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='unresolved_news_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unresolved_news_type_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='map_unresolved_resolved_news_type_map',
            name='resolved_news_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_avm.resolved_news_type'),
        ),
        migrations.AddField(
            model_name='map_unresolved_resolved_news_type_map',
            name='unresolved_news_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_avm.unresolved_news_type', unique=True),
        ),
        migrations.AddField(
            model_name='map_unresolved_resolved_location',
            name='resolved_location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_avm.resolved_location'),
        ),
        migrations.AddField(
            model_name='map_unresolved_resolved_location',
            name='unresolved_location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_avm.unresolved_location', unique=True),
        ),
        migrations.AddField(
            model_name='article_parsed',
            name='source_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_avm.source'),
        ),
        migrations.AddField(
            model_name='article_parsed',
            name='unresolved_location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_avm.unresolved_location'),
        ),
        migrations.AddField(
            model_name='article_parsed',
            name='unresolved_news_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_avm.unresolved_news_type'),
        ),
        migrations.AddField(
            model_name='article_content',
            name='article_parsed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_avm.article_parsed'),
        ),
    ]
